const CACHE_KEY = 'msfamily_translations_cache';

// ─── Hardcoded Tamil Dictionary (instant, no API needed) ─────────
// Covers every common UI string used across the app
export const TAMIL_DICTIONARY: Record<string, string> = {
  // ── Navigation & Pages ──
  'Dashboard': 'முகப்பு',
  'Transactions': 'பரிவர்த்தனைகள்',
  'New Record': 'புதிய பதிவு',
  'Loans': 'கடன்கள்',
  'Analytics': 'பகுப்பாய்வு',
  'Calendar': 'நாட்காட்டி',
  'My Proofs': 'எனது ஆவணங்கள்',
  'Family Hub': 'குடும்ப மையம்',
  'Live Tracking': 'நேரடி கண்காணிப்பு',
  'Settings': 'அமைப்புகள்',
  'Notifications': 'அறிவிப்புகள்',
  'Savings': 'சேமிப்பு',
  'Admin Panel': 'நிர்வாக குழு',
  'Help': 'உதவி',

  // ── Settings Page ──
  'Manage your preferences and account': 'உங்கள் விருப்பங்களையும் கணக்கையும் நிர்வகிக்கவும்',
  'Appearance': 'தோற்றம்',
  'Light': 'ஒளி',
  'Dark': 'இருட்டு',
  'System': 'கணினி',
  'Language': 'மொழி',
  'Account': 'கணக்கு',
  'Push Notifications': 'புஷ் அறிவிப்புகள்',
  'Receive alerts and reminders': 'எச்சரிக்கைகள் மற்றும் நினைவூட்டல்களைப் பெறுங்கள்',
  'Sound': 'ஒலி',
  'Play sound on notification': 'அறிவிப்பின் போது ஒலி எழுப்பு',
  'Reminder Frequency': 'நினைவூட்டல் அதிர்வெண்',
  'How often to receive reminders': 'எவ்வளவு அடிக்கடி நினைவூட்டல்கள் பெற வேண்டும்',
  'Daily': 'தினசரி',
  'Weekly': 'வாராந்திர',
  'Monthly': 'மாதாந்திர',
  'Off': 'அணைக்கவும்',
  'Security': 'பாதுகாப்பு',
  'App Lock': 'செயலி பூட்டு',
  'Require PIN to open app': 'செயலியைத் திறக்க PIN தேவை',
  'Biometric Unlock': 'பயோமெட்ரிக் திறப்பு',
  'Use fingerprint or Face ID': 'கைரேகை அல்லது முக அடையாளம் பயன்படுத்தவும்',
  'Data Management': 'தரவு மேலாண்மை',
  'Export Data': 'தரவை ஏற்றுமதி செய்',
  'Download your transactions as JSON': 'உங்கள் பரிவர்த்தனைகளை JSON ஆக பதிவிறக்கவும்',
  'Export': 'ஏற்றுமதி',
  'Clear Translation Cache': 'மொழிபெயர்ப்பு தற்காலிக சேமிப்பை அழி',
  'Removes saved translations': 'சேமிக்கப்பட்ட மொழிபெயர்ப்புகளை நீக்கும்',
  'Clear': 'அழி',
  'Reset All Settings': 'அனைத்து அமைப்புகளையும் மீட்டமை',
  'Restore to defaults': 'இயல்புநிலைக்கு மீட்டமை',
  'Reset': 'மீட்டமை',
  'Sign Out': 'வெளியேறு',
  'Theme updated': 'தீம் புதுப்பிக்கப்பட்டது',
  'Name updated successfully': 'பெயர் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
  'Failed to update name': 'பெயரைப் புதுப்பிக்க முடியவில்லை',
  'Notifications enabled': 'அறிவிப்புகள் இயக்கப்பட்டன',
  'Notifications disabled': 'அறிவிப்புகள் முடக்கப்பட்டன',
  'Sound on': 'ஒலி இயக்கப்பட்டது',
  'Sound off': 'ஒலி முடக்கப்பட்டது',
  'Reminder frequency updated': 'நினைவூட்டல் அதிர்வெண் புதுப்பிக்கப்பட்டது',
  'Translation cache cleared': 'மொழிபெயர்ப்பு தற்காலிக சேமிப்பு அழிக்கப்பட்டது',
  'Settings reset to default': 'அமைப்புகள் இயல்புநிலைக்கு மீட்டமைக்கப்பட்டன',
  'Data exported successfully': 'தரவு வெற்றிகரமாக ஏற்றுமதி செய்யப்பட்டது',
  'Export failed': 'ஏற்றுமதி தோல்வியடைந்தது',
  'Coming soon': 'விரைவில் வரும்',
  'App Version': 'செயலி பதிப்பு',
  'Role': 'பங்கு',

  // ── Security Feature Strings ──
  'Security Enabled': 'பாதுகாப்பு இயக்கப்பட்டது',
  'Security Disabled': 'பாதுகாப்பு முடக்கப்பட்டது',
  'Device lock not configured': 'சாதனப் பூட்டு அமைக்கப்படவில்லை',
  'Set up PIN, pattern, or password in device settings': 'சாதன அமைப்புகளில் PIN, பேட்டர்ன் அல்லது கடவுச்சொல் அமைக்கவும்',
  'No biometric enrolled': 'பயோமெட்ரிக் பதிவு செய்யப்படவில்லை',
  'Enable App Lock first': 'முதலில் செயலி பூட்டை இயக்கவும்',
  'Authentication failed': 'அங்கீகாரம் தோல்வியடைந்தது',
  'Checking device security...': 'சாதனப் பாதுகாப்பைச் சரிபார்க்கிறது...',
  'Available on Android app only': 'ஆண்ட்ராய்டு செயலியில் மட்டுமே கிடைக்கும்',
  'Install the APK to use security features': 'பாதுகாப்பு அம்சங்களைப் பயன்படுத்த APK ஐ நிறுவவும்',
  'Open Settings': 'அமைப்புகளைத் திற',
  'Not supported on this device': 'இந்தச் சாதனத்தில் ஆதரிக்கப்படவில்லை',
  'Use fingerprint to unlock': 'திறக்க கைரேகையைப் பயன்படுத்தவும்',
  'Use face unlock': 'முக அடையாளத்தைப் பயன்படுத்தவும்',
  'Enroll': 'பதிவு செய்',
  'Verifying...': 'சரிபார்க்கிறது...',
  'App is locked': 'செயலி பூட்டப்பட்டுள்ளது',
  'Unlock': 'திற',
  'Translations are AI-powered and cached locally': 'மொழிபெயர்ப்புகள் AI மூலம் இயக்கப்பட்டு உள்ளூரில் சேமிக்கப்படும்',

  // ── Layout & General ──
  'Finance Hub': 'நிதி மையம்',
  'Welcome back': 'மீண்டும் வரவேற்கிறோம்',
  'MS Family': 'எம்.எஸ் குடும்பம்',
  'Guest User': 'விருந்தினர்',
  'Guest': 'விருந்தினர்',
  'Cancel': 'ரத்து செய்',
  'Are you sure you want to sign out of your account?': 'உங்கள் கணக்கிலிருந்து வெளியேற விரும்புகிறீர்களா?',
  'Close': 'மூடு',
  'Save': 'சேமி',
  'Delete': 'நீக்கு',
  'Edit': 'திருத்து',
  'Add': 'சேர்',
  'Search': 'தேடு',
  'Filter': 'வடிகட்டு',
  'All': 'அனைத்தும்',
  'Today': 'இன்று',
  'Yesterday': 'நேற்று',
  'This Week': 'இந்த வாரம்',
  'This Month': 'இந்த மாதம்',
  'Total': 'மொத்தம்',
  'Income': 'வருமானம்',
  'Expense': 'செலவு',
  'Transfer': 'பரிமாற்றம்',
  'Amount': 'தொகை',
  'Category': 'வகை',
  'Description': 'விளக்கம்',
  'Date': 'தேதி',
  'Time': 'நேரம்',
  'income': 'வருமானம்',
  'expense': 'செலவு',
  'Member': 'உறுப்பினர்',
  'Type': 'வகை',
  'No data found': 'தரவு இல்லை',
  'Loading...': 'ஏற்றுகிறது...',
  'Error': 'பிழை',
  'Success': 'வெற்றி',
  'Confirm': 'உறுதிசெய்',
  'Back': 'பின்னால்',
  'Next': 'அடுத்து',
  'Previous': 'முந்தைய',
  'Submit': 'சமர்ப்பி',
  'Refresh data': 'தரவைப் புதுப்பி',

  // ── Dashboard ──
  'Overview': 'மேலோட்டம்',
  'Recent Transactions': 'சமீபத்திய பரிவர்த்தனைகள்',
  'Quick Actions': 'விரைவு செயல்கள்',
  'Balance': 'இருப்பு',
  'This month': 'இந்த மாதம்',
  'Last month': 'கடந்த மாதம்',
  'View All': 'அனைத்தையும் காண்',
  'Total Balance': 'மொத்த இருப்பு',
  'Savings Rate': 'சேமிப்பு விகிதம்',
  'Budget Limit': 'பட்ஜெட் வரம்பு',
  'Total Income': 'மொத்த வருமானம்',
  'Total Expenses': 'மொத்த செலவுகள்',
  'Budget Exceeded': 'பட்ஜெட் மீறப்பட்டது',
  'Add New Record': 'புதிய பதிவு சேர்',
  'Record income or expense': 'வருமானம் அல்லது செலவை பதிவு செய்',
  'Income vs Expense': 'வருமானம் எதிர் செலவு',
  'Top Categories': 'முன்னணி வகைகள்',
  'No transaction data yet': 'பரிவர்த்தனை தரவு இல்லை',
  'No expense data': 'செலவு தரவு இல்லை',
  'Savings Goal': 'சேமிப்பு இலக்கு',
  'saved': 'சேமிக்கப்பட்டது',
  'to go': 'மீதமுள்ளது',
  'records': 'பதிவுகள்',
  'No transactions yet. Add your first one!': 'பரிவர்த்தனைகள் இல்லை. முதல் பதிவைச் சேர்க்கவும்!',
  'Show less': 'குறைவாக காட்டு',
  'Delete this transaction?': 'இந்த பரிவர்த்தனையை நீக்கவா?',

  // ── Transactions ──
  'Add Transaction': 'பரிவர்த்தனையைச் சேர்',
  'No transactions found': 'பரிவர்த்தனைகள் எதுவும் இல்லை',
  'Newest First': 'புதியது முதலில்',
  'Oldest First': 'பழையது முதலில்',
  'Sort by': 'வரிசைப்படுத்து',
  'Filters': 'வடிகட்டிகள்',
  'Advanced Filters': 'மேம்பட்ட வடிகட்டிகள்',
  'Clear All': 'அனைத்தையும் அழி',
  'All Categories': 'அனைத்து வகைகள்',
  'Sort By': 'வரிசைப்படுத்து',
  'Date Range': 'தேதி வரம்பு',
  'Highest Amount': 'அதிக தொகை',
  'Lowest Amount': 'குறைந்த தொகை',
  'Total Count': 'மொத்த எண்ணிக்கை',
  'Net': 'நிகர',
  'No transactions match your filters': 'உங்கள் வடிகட்டிகளுக்கு பரிவர்த்தனைகள் இல்லை',
  'Clear Filters': 'வடிகட்டிகளை அழி',
  'records found': 'பதிவுகள் கிடைத்தன',
  'Page': 'பக்கம்',
  'of': 'இல்',
  'Notes': 'குறிப்புகள்',
  'Receipt Proof': 'ரசீது ஆதாரம்',
  'View Full': 'முழுமையாக காண்',
  'Delete Transaction': 'பரிவர்த்தனையை நீக்கு',
  'Export History': 'ஏற்றுமதி வரலாறு',
  'From Date': 'தொடக்க தேதி',
  'To Date': 'முடிவு தேதி',
  'Generate PDF': 'PDF உருவாக்கு',
  'Generating...': 'உருவாக்குகிறது...',
  'Actions': 'செயல்கள்',
  'Search by category, notes, amount, or member...': 'வகை, குறிப்புகள், தொகை அல்லது உறுப்பினர் மூலம் தேடவும்...',

  // ── Add Transaction ──
  'Record Added!': 'பதிவு சேர்க்கப்பட்டது!',
  'Redirecting to dashboard...': 'முகப்பிற்கு திரும்புகிறது...',
  'Send': 'அனுப்பு',
  'Send To (Recipient)': 'யாருக்கு அனுப்ப (பெறுநர்)',
  'Assign Record To': 'பதிவை ஒதுக்கு',
  'Confirm Record': 'பதிவை உறுதிசெய்',
  'Saving...': 'சேமிக்கிறது...',
  'Receipt Attached': 'ரசீது இணைக்கப்பட்டது',
  'Scanning': 'ஸ்கேன் செய்கிறது',
  'Scanned': 'ஸ்கேன் செய்யப்பட்டது',
  'AI is extracting amount & date...': 'AI தொகை மற்றும் தேதியை எடுக்கிறது...',
  'Proof will be securely stored with this record.': 'ஆதாரம் பாதுகாப்பாக சேமிக்கப்படும்.',
  'Optional details...': 'விருப்ப விவரங்கள்...',
  'View Full Image': 'முழு படத்தைக் காண தட்டவும்',
  'Extracting...': 'பிரித்தெடுக்கிறது...',
  'Scan Failed': 'ஸ்கேன் தோல்வி',
  'Smart Scanned': 'ஸ்மார்ட் ஸ்கேன் முடிந்தது',

  // ── Loans ──
  'Add Loan': 'கடன் சேர்',
  'Given': 'கொடுத்தது',
  'Taken': 'வாங்கியது',
  'Pending': 'நிலுவை',
  'Paid': 'செலுத்தப்பட்டது',
  'Interest Rate': 'வட்டி விகிதம்',
  'Due Date': 'நிலுவை தேதி',
  'EMI': 'மாத தவணை',
  'Track money given or taken': 'கொடுத்த அல்லது வாங்கிய பணத்தை கண்காணி',
  'To Receive': 'பெற வேண்டியது',
  'To Pay': 'செலுத்த வேண்டியது',
  'Net Balance': 'நிகர இருப்பு',
  'Active': 'செயலில்',
  'Settled': 'தீர்க்கப்பட்டது',
  'Lent': 'கொடுத்தது',
  'Borrowed': 'வாங்கியது',
  'Search people...': 'நபர்களை தேடு...',
  'No records found tracking debts or loans.': 'கடன் பதிவுகள் இல்லை.',
  '+ Add First Record': '+ முதல் பதிவைச் சேர்',
  'Mark Settled': 'தீர்க்கப்பட்டது எனக் குறி',
  'Record Loan / Debt': 'கடன் / கடமை பதிவு',
  'I Lent Money': 'நான் பணம் கொடுத்தேன்',
  'I Borrowed': 'நான் கடன் வாங்கினேன்',
  'Person Name': 'நபரின் பெயர்',
  'Loan Label': 'கடன் வகை',
  'Standard Split': 'பொது கடன்',
  'Monthly EMI': 'மாத தவணை',
  'Weekly Lenture': 'வாராந்திர கடன்',
  'Date Given': 'கொடுத்த தேதி',
  'Short Note': 'சிறு குறிப்பு',
  'Save Record': 'பதிவைச் சேமி',
  'Loading records...': 'பதிவுகளை ஏற்றுகிறது...',
  'Remind Every Week On': 'ஒவ்வொரு வாரமும் நினைவூட்டு',
  'Delete Record': 'பதிவை நீக்கு',
  'Paid Already (₹)': 'ஏற்கனவே செலுத்தியது (₹)',
  'Pending Balance': 'நிலுவைத் தொகை',
  'Remaining': 'மீதமுள்ளது',
  'Summary': 'சுருக்கம்',
  'You lent': 'நீங்கள் கடன் கொடுத்தீர்கள்',
  'You borrowed': 'நீங்கள் கடன் வாங்கினீர்கள்',
  'at': 'இல்',
  'from': 'இருந்து',
  'to': 'க்கு',
  'Due Date Reminder 🔔': 'நிலுவை தேதி நினைவூட்டல் 🔔',
  'Monthly EMI Reminder 📅': 'மாதாந்திர EMI நினைவூட்டல் 📅',
  'Weekly Finance Reminder 🗓️': 'வாராந்திர நிதி நினைவூட்டல் 🗓️',
  'In': 'இன்னும்',
  'days': 'நாட்கள்',
  'Record updated!': 'பதிவு புதுப்பிக்கப்பட்டது!',
  'Record saved!': 'பதிவு சேமிக்கப்பட்டது!',
  'Marked as settled': 'தீர்க்கப்பட்டது எனக் குறிக்கப்பட்டது',
  'CSV exported!': 'CSV ஏற்றுமதி செய்யப்பட்டது!',
  'Delete Permanently?': 'நிரந்தரமாக நீக்கவா?',
  'This action cannot be undone. All data for this record will be lost forever.': 'இந்த செயலை மாற்ற முடியாது. இந்த பதிவின் அனைத்து தரவும் நிரந்தரமாக இழக்கப்படும்.',

  // ── Savings & Assets ──
  'Savings & Assets': 'சேமிப்பு மற்றும் சொத்துக்கள்',
  'Offline Mode - Showing cached rates': 'ஆஃப்லைன் பயன்முறை - சேமிக்கப்பட்ட விகிதங்களைக் காட்டுகிறது',
  'Live Rates Active': 'நேரடி விகிதங்கள் செயலில் உள்ளன',
  'Loading rates...': 'விகிதங்களை ஏற்றுகிறது...',
  'Pricing Source': 'விலை ஆதாரம்',
  'Live spot rates fetched directly from global markets.': 'உலகளாவிய சந்தைகளிலிருந்து நேரடியாகப் பெறப்பட்ட நேரடி விலைகள்.',
  'Displaying historically cached rates to conserve resources.': 'வளங்களைச் சேமிக்க வரலாற்று ரீதியாகச் சேமிக்கப்பட்ட விகிதங்களைக் காட்டுகிறது.',
  'Using AI estimated values due to network or service failure.': 'பிணையம் அல்லது சேவை தோல்வி காரணமாக AI மதிப்பிடப்பட்ட மதிப்புகளைப் பயன்படுத்துதல்.',
  'Last updated:': 'கடைசியாக புதுப்பிக்கப்பட்டது:',
  'Current Value': 'தற்போதைய மதிப்பு',
  'Total Invested': 'மொத்தம் முதலீடு செய்யப்பட்டது',
  'Profit / Loss': 'லாபம் / நஷ்டம்',
  'Asset Distribution': 'சொத்து விநியோகம்',
  'Investment Growth': 'முதலீட்டு வளர்ச்சி',
  'Gold 24K': 'தங்கம் 24K',
  'Gold 22K': 'தங்கம் 22K',
  'Your Assets': 'உங்கள் சொத்துக்கள்',
  'New Investment': 'புதிய முதலீடு',
  'Asset': 'சொத்து',
  'Qty': 'அளவு',
  'Purchase Total': 'வாங்கிய மொத்தம்',
  'Current Val': 'தற்போதைய மதிப்பு',
  'No investments added yet. Start tracking your savings!': 'இன்னும் முதலீடுகள் சேர்க்கப்படவில்லை. உங்கள் சேமிப்பைக் கண்காணிக்கத் தொடங்குங்கள்!',
  'Units': 'அலகுகள்',
  'Edit Investment': 'முதலீட்டைத் திருத்து',
  'Asset Type': 'சொத்து வகை',
  'Total Cost (₹)': 'மொத்த செலவு (₹)',
  'Live API Value: ': 'நேரடி API மதிப்பு: ',
  'Purchase Date': 'வாங்கிய தேதி',
  'Bill / Proof (Optional)': 'பில் / ஆதாரம் (விருப்பமானது)',
  'Bill Attached': 'பில் இணைக்கப்பட்டுள்ளது',
  'Tap to Capture / Upload': 'பிடிக்க / பதிவேற்ற தட்டவும்',
  'Bought from GRT Jewellers': 'ஜி.ஆர்.டி ஜூவல்லர்ஸில் வாங்கப்பட்டது',
  'Save Investment': 'முதலீட்டைச் சேமி',
  'Asset updated!': 'சொத்து புதுப்பிக்கப்பட்டது!',
  'Asset added!': 'சொத்து சேர்க்கப்பட்டது!',
  'Asset deleted': 'சொத்து நீக்கப்பட்டது',
  'Are you sure you want to delete this asset?': 'நிச்சயமாக இந்த சொத்தை நீக்க வேண்டுமா?',
  'Processing image...': 'படம் செயலாக்கப்படுகிறது...',
  'Image attached': 'படம் இணைக்கப்பட்டது',
  'Failed to fetch live rates': 'நேரடி விகிதங்களைப் பெறுவதில் தோல்வி',
  'Using saved data': 'சேமிக்கப்பட்ட தரவைப் பயன்படுத்துகிறது',
  'Estimated values': 'மதிப்பிடப்பட்ட மதிப்புகள்',
  'Live market data': 'நேரடி சந்தை தரவு',
  'Gold': 'தங்கம்',
  'Silver': 'வெள்ளி',
  'Other': 'மற்றவை',
  '24K (99.9%)': '24K (99.9%)',
  '22K (91.6%)': '22K (91.6%)',
  'KDM': 'KDM',
  '18K': '18K',
  'Gold Coins': 'தங்க நாணயங்கள்',
  'Gold Bars': 'தங்கக் கட்டிகள்',
  'Silver Bars': 'வெள்ளிக் கட்டிகள்',
  'Silver Coins': 'வெள்ளி நாணயம்',
  'Silver Jewelry': 'வெள்ளி ஆபரணங்கள்',
  'Sterling Silver': 'ஸ்டெர்லிங் வெள்ளி',
  'Stocks': 'பங்குகள்',
  'Mutual Funds': 'மியூச்சுவல் ஃபண்டுகள்',
  'Crypto': 'கிரிப்டோ',
  'Real Estate': 'ரியல் எஸ்டேட்',
  'Bonds': 'பத்திரங்கள்',
  'FD': 'நிலை வைப்பு',
  'Monthly Trend': 'மாதாந்திர போக்கு',
  'Intelligence Node': 'நுண்ணறிவு மையம்',
  'Cross-referencing financial matrix': 'நிதி மேட்ரிக்ஸை குறுக்கு ஆய்வு',
  'All Time': 'முழு நேரம்',
  'EXPORT PDF': 'PDF ஏற்றுமதி',
  'Gross Inflow': 'மொத்த வரவு',
  'Capital Burn': 'மூலதன செலவு',
  'Net Retained': 'நிகர சேமிப்பு',
  'Save Velocity': 'சேமிப்பு வேகம்',
  'Liquidity Velocity': 'பண வேகம்',
  'Resource Allocation': 'வள ஒதுக்கீடு',
  'Total Out': 'மொத்த வெளியீடு',
  'Entity Impact Ratio': 'நிறுவன தாக்க விகிதம்',
  'Synaptic Insights': 'நரம்பு நுண்ணறிவுகள்',
  'AI Generated Strategies': 'AI உருவாக்கிய உத்திகள்',
  'Spending Pattern Alert': 'செலவு முறை எச்சரிக்கை',
  'Exceptional Discipline': 'சிறப்பான ஒழுக்கம்',
  'Capital Erosion Risk': 'மூலதன அரிப்பு ஆபத்து',
  'Asymmetric Spending': 'சமச்சீரற்ற செலவு',
  'System Stable': 'அமைப்பு நிலையானது',
  'No liquidity data for selected period.': 'தேர்ந்தெடுத்த காலத்திற்கு தரவு இல்லை.',
  'Initialize allocations to view.': 'காண ஒதுக்கீடுகளை தொடங்கவும்.',
  'No entities active.': 'செயலில் உள்ள நிறுவனங்கள் இல்லை.',

  // ── My Proofs ──
  'Upload Proof': 'ஆவணத்தை பதிவேற்றம் செய்',
  'No proofs yet': 'ஆவணங்கள் இல்லை',
  'Smart Scan': 'ஸ்மார்ட் ஸ்கேன்',
  'Camera': 'கேமரா',
  'Gallery': 'காலரி',

  // ── Family Hub ──
  'Family Members': 'குடும்ப உறுப்பினர்கள்',
  'Family Overview': 'குடும்ப மேலோட்டம்',

  // ── Live Tracking ──
  'Share Location': 'இருப்பிடத்தைப் பகிர்',
  'Stop Sharing': 'பகிர்வதை நிறுத்து',
  'Battery': 'பேட்டரி',
  'Last Updated': 'கடைசியாக புதுப்பிக்கப்பட்டது',

  // ── Calendar ──
  'No events': 'நிகழ்வுகள் இல்லை',

  // ── Preferences Sync ──
  'Preferences saved': 'விருப்பங்கள் சேமிக்கப்பட்டன',
  'Preferences synced': 'விருப்பங்கள் ஒத்திசைக்கப்பட்டன',
  'Saved to cloud': 'கிளவுட்டில் சேமிக்கப்பட்டது',

  // ── Login Page ──
  'Login': 'உள்நுழை',
  'Sign Up': 'பதிவு செய்',
  'Email': 'மின்னஞ்சல்',
  'Password': 'கடவுச்சொல்',
  'Full Name': 'முழு பெயர்',
  'Forgot Password?': 'கடவுச்சொல் மறந்துவிட்டதா?',
  "Don't have an account?": 'கணக்கு இல்லையா?',
  'Already have an account?': 'ஏற்கனவே கணக்கு உள்ளதா?',

  // ── Categories ──
  'Food': 'உணவு',
  'Entertainment': 'பொழுதுபோக்கு',
  'Health': 'ஆரோக்கியம்',
  'Education': 'கல்வி',
  'Groceries': 'மளிகை',
  'Salary': 'சம்பளம்',
  'Freelance': 'ஃப்ரீலான்ஸ்',
  'Investment': 'முதலீடு',
  'Gift': 'பரிசு',
  'Bonus': 'போனஸ்',

  // ── Calendar ──
  'Selected Date': 'தேர்ந்தெடுக்கப்பட்ட தேதி',
  'No records on this date': 'இந்த தேதியில் பதிவுகள் இல்லை',
  'Add a transaction to see it here': 'இங்கே காண ஒரு பரிவர்த்தனையைச் சேர்க்கவும்',

  // ── Family Overview ──
  'Family Ecosystem': 'குடும்ப சூழலமைப்பு',
  "Your family's combined financial health at a glance": 'உங்கள் குடும்பத்தின் ஒருங்கிணைந்த நிதி நிலை',
  'Net Savings': 'நிகர சேமிப்பு',
  'Top Earner': 'அதிக வருமானம்',
  'Top Spender': 'அதிக செலவு',
  'Best Saver': 'சிறந்த சேமிப்பாளர்',
  'Spend Ratio': 'செலவு விகிதம்',
  'Member Comparison': 'உறுப்பினர் ஒப்பீடு',
  'Member Profiles': 'உறுப்பினர் விவரங்கள்',
  'No Family Members Yet': 'குடும்ப உறுப்பினர்கள் இல்லை',
  'Start adding transactions with member names to see family insights.': 'குடும்ப நுண்ணறிவுகளைக் காண உறுப்பினர் பெயர்களுடன் பரிவர்த்தனைகளைச் சேர்க்கத் தொடங்குங்கள்.',
  'Loading family data...': 'குடும்ப தரவை ஏற்றுகிறது...',
  'Savings Champion': 'சேமிப்பு சாミュニன்',
  'Disciplined': 'ஒழுக்கமான',
  'Over Budget': 'பட்ஜெட் மீறியது',

  // ── My Proofs ──
  'All Documents': 'அனைத்து ஆவணங்கள்',
  'Identity': 'அடையாளம்',
  'Financial': 'நிதி',
  'Vehicle': 'வாகனம்',
  'Search proofs...': 'ஆவணங்களை தேடு...',
  'Upload New Proof': 'புதிய ஆவணத்தை பதிவேற்றம்',
  'No Documents Found': 'ஆவணங்கள் இல்லை',
  'Upload your first proof to secure it in your digital locker.': 'உங்கள் டிஜிட்டல் லாக்கரில் பாதுகாக்க முதல் ஆவணத்தை பதிவேற்றவும்.',
  'Document Details': 'ஆவண விவரங்கள்',
  'Document Number': 'ஆவண எண்',
  'Edit Details': 'விவரங்களை திருத்து',
  'Save Changes': 'மாற்றங்களை சேமி',
  'Confirm Delete': 'நீக்குவதை உறுதிசெய்',
  'Are you sure you want to delete this document?': 'இந்த ஆவணத்தை நீக்க விரும்புகிறீர்களா?',
  'Deleting...': 'நீக்குகிறது...',
  'Delete Document': 'ஆவணத்தை நீக்கு',
  'Front Side': 'முன் பக்கம்',
  'Back Side': 'பின் பக்கம்',
  'Add Back Image': 'பின்புற படத்தைச் சேர்',
  'Save Document': 'ஆவணத்தை சேமி',
  'Title': 'தலைப்பு',
  'AI Summary': 'AI சுருக்கம்',

  // ── Notifications ──
  'Mark all read': 'அனைத்தையும் படித்ததாக குறி',
  'Clear all': 'அனைத்தையும் அழி',
  'Loading notifications...': 'அறிவிப்புகளை ஏற்றுகிறது...',
  'No notifications yet.': 'இன்னும் அறிவிப்புகள் இல்லை.',
  'Mark as Read': 'படித்ததாக குறி',
  'Smart Reminders': 'ஸ்மார்ட் நினைவூட்டல்கள்',
  'Active — auto reminders for expenses': 'செயலில் உள்ளது — செலவுகளுக்கான தானியங்கி நினைவூட்டல்கள்',
  'Morning': 'காலை',
  'Afternoon': 'மதியம்',
  'Evening': 'மாலை',
  'Night': 'இரவு',
  'Tea': 'டீ',
  'Breakfast': 'காலை உணவு',
  'Milk': 'பால்',
  'Lunch': 'மதிய உணவு',
  'Snacks': 'சிற்றுண்டி',
  'Fuel': 'எரிபொருள்',
  'Dinner': 'இரவு உணவு',
  'Daily Expense Entry': 'தினசரி செலவு பதிவு',
  'Pending Records': 'நிலுவையில் உள்ள பதிவுகள்',
  'Max 1 notification per time slot to prevent spam. Notifications work even when the app is closed.': 'ஸ்பேமைத் தவிர்க்க ஒரு நேரத்திற்கு 1 அறிவிப்பு மட்டுமே. ஆப்ஸ் மூடப்பட்டிருந்தாலும் இது வேலை செய்யும்.',

  // ── Login ──
  'Weak': 'பலவீனமான',
  'Medium': 'நடுத்தர',
  'Strong': 'வலுவான',
  'Password strength:': 'கடவுச்சொல் வலிமை:',
  'Use 8+ chars with uppercase, number & symbol': 'பெரிய எழுத்து, எண் மற்றும் குறியீட்டைக் கொண்ட 8+ எழுத்துக்களைப் பயன்படுத்தவும்',
  'Sign in to your family dashboard': 'உங்கள் குடும்ப டேஷ்போர்டில் உள்நுழையவும்',
  'Create your family account': 'உங்கள் குடும்ப கணக்கை உருவாக்கவும்',
  'Full Name (e.g., Dad, Mom, Son)': 'முழு பெயர் (எ.கா., அப்பா, அம்மா, மகன்)',
  'Email address': 'மின்னஞ்சல் முகவரி',
  'Password (min 6 characters)': 'கடவுச்சொல் (குறைந்தபட்சம் 6 எழுத்துக்கள்)',
  'Confirm password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
  'Remember me': 'என்னை நினைவில் கொள்',
  'Terms of Service': 'சேவை விதிமுறைகள்',
  'Privacy Policy': 'தனியுரிமை கொள்கை',
  'I agree to the': 'நான் ஏற்கிறேன்',
  'and': 'மற்றும்',
  'Access Dashboard': 'டேஷ்போர்டை அணுகவும்',
  'Create Account': 'கணக்கை உருவாக்கு',
  'No account yet? ': 'இன்னும் கணக்கு இல்லையா? ',
  'Already a member? ': 'ஏற்கனவே உறுப்பினரா? ',
  'Sign In': 'உள்நுழை',
  'Sign up each family member (Shanmugasundaram, Arulprakash, Malathi, Subiksha) with unique emails. All members share the same financial dashboard.': 'ஒவ்வொரு குடும்ப உறுப்பினரையும் (சண்முகசுந்தரம், அருள்பிரகாஷ், மாலதி, சுபிக்ஷா) தனித்துவமான மின்னஞ்சல்களுடன் பதிவு செய்யவும். அனைத்து உறுப்பினர்களும் ஒரே நிதி டேஷ்போர்டைப் பகிர்ந்து கொள்கிறார்கள்.',

  // ── Live Tracking ──
  'Enable Location': 'இருப்பிடத்தை இயக்கு',
  'We need your location to show you on the map and share it with your family.': 'வரைபடத்தில் உங்களைக் காட்டவும் உங்கள் குடும்பத்துடன் பகிரவும் உங்கள் இருப்பிடம் தேவை.',
  'Allow Location Access': 'இருப்பிட அணுகலை அனுமதி',
  'You': 'நீங்கள்',
  'Your live position': 'உங்கள் நேரடி நிலை',
  'Loading map...': 'வரைபடத்தை ஏற்றுகிறது...',
  'Map': 'வரைபடம்',
  'Sat': 'செயற்கைக்கோள்',
  'Terrain': 'நிலப்பரப்பு',
  'My location': 'என் இருப்பிடம்',
  'Sharing': 'பகிர்கிறது',
  'Private': 'தனிப்பட்ட',
  'No family members sharing': 'பகிரும் குடும்ப உறுப்பினர்கள் இல்லை',
  'Family Member': 'குடும்ப உறுப்பினர்',
  'Online': 'ஆன்லைன்',
  'Offline': 'ஆஃப்லைன்',
  'Directions': 'வழிகள்',
  'Call': 'அழைக்க',

  // ── Missing Strings ──
  'Microphone access is required for calls. Please allow microphone permission.': 'அழைப்புகளுக்கு மைக்ரோஃபோன் அணுகல் தேவை. மைக்ரோஃபோன் அனுமதியை வழங்கவும்.',
  'Could not delete. Please try again.': 'நீக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'Failed to save loan.': 'கடனைச் சேமிக்க முடியவில்லை.',
  'Forgot password?': 'கடவுச்சொல் மறந்துவிட்டதா?',
  'Terms & Conditions would be shown here.': 'விதிமுறைகள் மற்றும் நிபந்தனைகள் இங்கே காட்டப்படும்.',
  'Privacy Policy would be shown here.': 'தனியுரிமைக் கொள்கை இங்கே காட்டப்படும்.',
  'Please upload a valid image file.': 'செல்லுபடியாகும் படக் கோப்பைப் பதிவேற்றவும்.',
  'AI analysis failed. Please enter details manually.': 'AI பகுப்பாய்வு தோல்வியடைந்தது. விவரங்களை கைமுறையாக உள்ளிடவும்.',
  'Are you sure you want to clear all notifications?': 'அனைத்து அறிவிப்புகளையும் அழிக்க விரும்புகிறீர்களா?',
  'Failed to delete. Try again.': 'நீக்குவதில் தோல்வி. மீண்டும் முயற்சிக்கவும்.',
  'Please select both From and To dates': 'தொடக்கம் மற்றும் முடிவு தேதிகளைத் தேர்ந்தெடுக்கவும்',
  'No transactions found in this date range': 'இந்த தேதிகளில் பரிவர்த்தனைகள் காணப்படவில்லை',
  'Failed to generate PDF': 'PDF உருவாக்குவதில் தோல்வி',
  'Translated successfully and cached locally': 'முழுக்க மொழிபெயர்க்கப்பட்டு சாதனத்தில் சேமிக்கப்பட்டது',
  'Fetch Location': 'இருப்பிடத்தைப் பெறுக',
  'Location Request': 'இருப்பிட கோரிக்கை',
  'checked your location': 'உங்கள் இருப்பிடத்தைப் பார்த்தார்',
  "success', proof.back_image_url ? 'Both images saved!' : 'Image saved successfully!": 'வெற்றி, படம் வெற்றிகரமாக சேமிக்கப்பட்டது!',

  // ── Call Screen ──
  'Encrypted': 'மறையாக்கப்பட்டது',
  'Voice Call': 'குரல் அழைப்பு',
  'Calling...': 'அழைக்கிறது...',
  'Incoming Call': 'உள்வரும் அழைப்பு',
  'Call Ended': 'அழைப்பு முடிந்தது',
  'Connected': 'இணைக்கப்பட்டது',
  'Mute': 'ஒலியடக்கு',
  'Unmute': 'ஒலி திற',
  'Speaker': 'ஸ்பீக்கர்',
  'Accept': 'ஏற்கவும்',
  'Decline': 'நிராகரி',
  'End': 'முடி',
  'Microphone access denied. Please enable it in your browser/device settings.': 'மைக்ரோஃபோன் அணுகல் மறுக்கப்பட்டது. உலாவி/சாதன அமைப்புகளில் இயக்கவும்.',

  // ── User Names ──
  'ShanmugaSundaram': 'சண்முகசுந்தரம்',
  'Shanmugasundaram': 'சண்முகசுந்தரம்',
  'ArulPrakash': 'அருள்பிரகாஷ்',
  'Arulprakash': 'அருள்பிரகாஷ்',
  'Malathi': 'மாலதி',
  'Subiksha': 'சுபிக்க்ஷா',
  'Myself': 'நானே',
  'User': 'பயனர்',
};

// Load cache from localStorage
const loadCache = (): Record<string, string> => {
  try {
    const cached = localStorage.getItem(CACHE_KEY);
    return cached ? JSON.parse(cached) : {};
  } catch {
    return {};
  }
};

// Save cache to localStorage
const saveCache = (cache: Record<string, string>): void => {
  try {
    localStorage.setItem(CACHE_KEY, JSON.stringify(cache));
  } catch (e) {
    console.error('Failed to save translation cache:', e);
  }
};

const translationCache = loadCache();

// Pre-populate cache with dictionary entries (so they're available instantly)
Object.entries(TAMIL_DICTIONARY).forEach(([key, value]) => {
  if (!translationCache[key]) {
    translationCache[key] = value;
  }
});
saveCache(translationCache);

export const getCachedTranslation = (text: string): string | null => translationCache[text] || TAMIL_DICTIONARY[text] || null;
export const getAllCachedTranslations = (): Record<string, string> => ({ ...TAMIL_DICTIONARY, ...translationCache });

/**
 * Translates a given text to Tamil using the local dictionary.
 */
export const translateToTamil = async (text: string): Promise<string> => {
  if (!text || typeof text !== 'string') return text;

  if (TAMIL_DICTIONARY[text]) {
    return TAMIL_DICTIONARY[text];
  }

  if (translationCache[text]) {
    return translationCache[text];
  }

  return text; // Fallback to English if not found
};

/**
 * No-op prefetch since we are completely offline.
 */
export const prefetchTranslations = async (texts: string[]): Promise<void> => {
  return;
};
